### ISSUE TITLE
artifacts in the mid

### ISSUE THREAD

**Issue by infamedavid** [garnetgrimm/Omnimango-Manuals#1]
the module works very well, but I'm getting some weird artifacts in the mid-high frequencies, this happens even with the bass lines (which I have filtered through a low pass)

**Comment by garnetgrimm** [comment]
Hey David, I am so sorry I can't believe I never received any sort of notification for this issue so I am just seeing it for the first time this morning. I will work on both of these open issues hopefully after work tomorrow, or at the latest this weekend.  Can you attach an audio clip of the problem along with a simple patch that causes the problem?

**Comment by garnetgrimm** [comment]
![image](https://user-images.githubusercontent.com/14164368/135281616-f9ed2b28-dcd2-4e6d-9232-cacd95df3728.png)
Nevermind, I definitely see your point. I will be looking in to this ASAP

**Comment by garnetgrimm** [comment]
Fixed as far as I can tell. An update should go out later tonight or tomorrow. Feel free to let me know if this helps you out.
